### ISSUE TITLE
Индексирование использований в монорепозитории

### ISSUE THREAD

**Issue by Nelfimov** [torin-asakura/Intellij#1]
На последних версиях IntelliJ обнаружен баг с отображением использований (Find Usages) компонентов в проекте.

Например, [doc-web](https://github.com/delta-doc/web). Компонент `Button` (`@ui/button`) отображается использование только в 3 местах:

<details>
<summary>Скрин</summary

<img width="1544" alt="image" src="https://github.com/torin-asakura/Intellij/assets/44067768/27bbe537-6e80-4e49-b97c-f2a539bbd508">

</details>

Хотя компонент присутствует по всему проекту.

Пример с `Input` (`@ui/input`):

<details>
<summary>Скрин</summary

![image](https://github.com/torin-asakura/Intellij/assets/44067768/e3dd1a43-b35b-4024-b0b3-0e8dfde00549)

</details>

Аналогичная проблема в WebStorm последних версий. Инвалидация кэшей не работает, проблема обнаружена на свежей установке IntelliJ.

**Comment by TorinAsakura** [comment]
## 1 эксперимент
Попробуй сделать несколько пакетов модулями айдии и проверь юзеджи

**Comment by Nelfimov** [comment]
Потрачено.

<details>
<summary>Настройка проекта</summary>

![image](https://github.com/torin-asakura/Intellij/assets/44067768/58db3631-3d2e-45da-83ef-ff5c7e532cb7)

</details>

<details>
<summary>Usages у иконки, которая есть в новом модуле</summary>

![image](https://github.com/torin-asakura/Intellij/assets/44067768/dc6ef7ed-8bb3-410b-af64-36d43d679880)

</details>

**Comment by Nelfimov** [comment]
Еще заметил нюанс:

`@ui/button`, `button.component.tsx` выдает такие usages:

<details>

![image](https://github.com/torin-asakura/Intellij/assets/44067768/457f4965-d8d7-4096-94fc-ff7eb3e14e79)

</details>

А `recovery-link.component.tsx` импортирует `button` вообще не из `ui`:

<details>

![image](https://github.com/torin-asakura/Intellij/assets/44067768/5d58125d-a9d9-4c50-8c1e-2eb463454c0b)

</details>

**Comment by Nelfimov** [comment]
## Результат эксперимента

Сделал такую структуру проекта:

<details>

<img width="1260" alt="Screenshot 2023-09-01 at 09 18 29" src="https://github.com/torin-asakura/Intellij/assets/44067768/aa0d0f67-9a01-43d5-a708-210c206c31ef">

</details>

Результат тот же:

<details>
<summary>`@ui/layout` Box</summary>

<img width="1019" alt="Screenshot 2023-09-01 at 09 18 57" src="https://github.com/torin-asakura/Intellij/assets/44067768/d1f9f492-e2ab-4e9d-8945-5796db16dd65">


</details>

<details>
<summary>`@ui/button`</summary>

<img width="1019" alt="Screenshot 2023-09-01 at 09 20 59" src="https://github.com/torin-asakura/Intellij/assets/44067768/6984a09e-2f85-46ba-a1bb-21605b83c11e">

</details>

Layout и Button есть в after-login.fragment, но по прежнему не отображаются.

**Comment by Nelfimov** [comment]
Еще попробовал в Library добавить `@ui/button` и `after-login` - не решило проблему

<details>
<summary>Структура проекта</summary>
<img width="1260" alt="image" src="https://github.com/torin-asakura/Intellij/assets/44067768/520b0925-5e9a-41e6-9731-bb34d963c463">


<details>

**Comment by Nelfimov** [comment]
Похоже на нашу проблему 

https://youtrack.jetbrains.com/issue/WEB-60790/Navigation-doesnt-work-in-the-import-statement-between-workspaces-when-using-yarn-pnp

**Comment by TorinAsakura** [comment]
Я тебе больше скажу - я нашёл свои старые тикеты трёхлетней давности, эта проблема уже решалась. Закрываю таску, ждём пока JB отдуплятся
